spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: test
    driver-class-name: org.h2.Driver

  #  env파일 설정
  config:
    import: optional:file:.env[.properties]
  #   Jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  #   flyway
  flyway:
    enabled: false
  #   sql
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
