spring:
  datasource:
    driverClassname: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  spring:
    config:
      import: optional:file:.env[.properties]