spring:
  datasource:
    driverClassname: org.mariadb.jdbc.Driver
    url: ${jdbc:mariadb://localhost:3305/delivery_api}
    username: ${root}
    password: ${root}
  spring:
    config:
      import: optional:file:.env[.properties]