spring:
  # h2
  datasource:
    url: jdbc:h2:tcp://localhost/~/delivery
    username: sa
    password:
    driver-class-name: org.h2.Driver

  #  env파일 설정
  config:
    import: optional:file:.env[.properties]
  #   Jpa
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  #   flyway
  flyway:
    enabled: false
